### ISSUE TITLE
Deletes all packages including nix

### ISSUE THREAD

**Issue by piq9117** [nmattia/homies#3]
Hello! thank you so much for this project! This has been the most helpful so far in setting up nix.

This is my `default.nix`
```Nix
{ nixpkgs ? import <nixpkgs> {} }:

let
  inherit (nixpkgs) pkgs;
  inherit (pkgs) haskellPackages;

  haskellDeps = ps: with ps; [
    stack
    dbmigrations
    cabal-helper
    cabal-install
  ];


  ghc = haskellPackages.ghcWithPackages haskellDeps;

  nixPackages = [
    ghc
    pkgs.gdb
    pkgs.zlib
    pkgs.postgresql
    pkgs.emacs
    pkgs.vim
    pkgs.couchdb
    pkgs.hyperledger-fabric
  ];
in
  if pkgs.lib.inNixShell
  then pkgs.mkShell
  { buildInputs = nixPackages;
    shellHook = ''
      $(zshrc)
    '';
  }
  else nixPackages
```

I run `nix-env -f default.nix -i --remove-all`. Then it installs and deletes all the previously install files as mentioned in the blog, one thing I didn't expect was it also deleted nix. What am I doing wrong?

It's not really a big issue coz I can just download nix again, then it works. I'm just curios if this was expected.

**Comment by nmattia** [comment]
Ah, right! You probably had nix installed through `nix-env -iA nix`? You can always add `pkgs.nix` to `nixPackages`, that should work.

**Comment by piq9117** [comment]
Thanks for the quick response! adding `pkgs.nix` works! thanks!
